package com.studyai.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.*

@Entity(tableName = "quizzes", foreignKeys = [ForeignKey(entity = TopicEntity::class, parentColumns = ["topicId"], childColumns = ["topicId"], onDelete = ForeignKey.CASCADE), ForeignKey(entity = StudentEntity::class, parentColumns = ["studentId"], childColumns = ["studentId"], onDelete = ForeignKey.CASCADE)], indices = [Index("topicId"), Index("studentId"), Index("quizId")])
data class QuizEntity(
    @PrimaryKey val quizId: String,
    val topicId: String,
    val studentId: String,
    val quizName: String,
    val quizDescription: String = "",
    val quizType: String,
    val difficultyLevel: String = "MEDIUM",
    val totalQuestions: Int = 10,
    val timeLimit: Int = 30,
    val negativeMarking: Boolean = true,
    val marksPerQuestion: Double = 1.0,
    val negativeMarkPerQuestion: Double = 0.25,
    val passingPercentage: Double = 60.0,
    val totalMarks: Double = 10.0,
    val isAutoGenerated: Boolean = true,
    val isShuffled: Boolean = true,
    val allowReview: Boolean = true,
    val allowRetry: Boolean = true,
    val maxAttempts: Int = 3,
    val isPublished: Boolean = true,
    val isActive: Boolean = true,
    val createdAt: Date = Date(),
    val updatedAt: Date = Date()
)

@Entity(tableName = "quiz_answers", foreignKeys = [ForeignKey(entity = QuizEntity::class, parentColumns = ["quizId"], childColumns = ["quizId"], onDelete = ForeignKey.CASCADE), ForeignKey(entity = StudentEntity::class, parentColumns = ["studentId"], childColumns = ["studentId"], onDelete = ForeignKey.CASCADE)], indices = [Index("quizId"), Index("studentId"), Index("questionId")])
data class QuizAnswerEntity(
    @PrimaryKey val answerId: String,
    val quizId: String,
    val questionId: String,
    val studentId: String,
    val questionText: String = "",
    val questionType: String = "",
    val studentAnswer: String = "",
    val correctAnswer: String = "",
    val explanation: String = "",
    val isCorrect: Boolean = false,
    val marksObtained: Double = 0.0,
    val totalMarks: Double = 1.0,
    val timeSpentSeconds: Int = 0,
    val attemptNumber: Int = 1,
    val confidence: Int = 0,
    val createdAt: Date = Date(),
    val answeredAt: Date = Date()
)
