package com.studyai.domain.model

import java.util.*

data class Quiz(
    val quizId: String,
    val topicId: String,
    val studentId: String,
    val quizName: String,
    val quizType: String,
    val totalQuestions: Int = 10,
    val timeLimit: Int = 30,
    val passingPercentage: Double = 60.0,
    val totalMarks: Double = 10.0,
    val isAutoGenerated: Boolean = true,
    val isPublished: Boolean = true,
    val createdAt: Date = Date(),
    val updatedAt: Date = Date()
)
